- name: Deploy frontend and backend containers from GitHub
  hosts: all
  become: yes

  vars:
    repo_url: "https://github.com/Teju-Aws/2nd10WeeksofCloudOps-main.git"
    app_path: "/root/project-1/"
    frontend_image: "frontend-app:latest"
    backend_image: "backend-app:latest"
    rds_host: "database-1.cpgg6ek8kwju.ap-south-1.rds.amazonaws.com"
    rds_user: "admin"
    rds_password: "Cloud123"
    rds_port: "3306"

  roles:
    - common
    - gitclone
    - frontend
    - backend

